name: Build
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:unit

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: dist/
